DSND-2871: Add structured logging charges-delta-consumer
companieshouse/charges-delta-consumer pull request #106
Opened 2024-10-01 08:49 UTC by crowlandsCH

* structured logging version added
* code refactored slightly for readability
* PR dependent on structured logging PRs

[DSND-2871](https://companieshouse.atlassian.net/browse/DSND-2871)

2024-10-03 16:03 UTC, cgregoryCH requested changes

2024-10-04 11:30 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/service/ApiClientServiceImpl.java
> +            LOGGER.error(PRIVATE_API_GENERIC_EXCEPTION, ex, DataMapHolder.getLogMap());
addressed in most recent commit

2024-10-04 11:30 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/service/ApiClientServiceImpl.java
> +            LOGGER.error(ERROR_RESPONSE_EXCEPTION, ex, DataMapHolder.getLogMap());
addressed in most recent commit

2024-10-04 11:30 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
> +            LOGGER.error(String.format(RETRYABLE_RESPONSE_ERROR_MESSAGE, httpStatus),
addressed in most recent commit

2024-10-04 11:30 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
> +            LOGGER.info(String.format(NON_RETRYABLE_RESPONSE_ERROR_MESSAGE,
addressed in most recent commit

2024-10-04 11:31 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
> +        DataMapHolder.get().companyNumber(companyNumber);
addressed in most recent commit

2024-10-04 11:31 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
> +        DataMapHolder.get().companyNumber("0");
addressed in most recent commit

2024-10-04 11:31 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/logging/LoggingKafkaListenerAspect.java
> +                LOGGER.info(String.format(EXCEPTION_MESSAGE,
addressed in most recent commit

2024-10-04 11:31 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/consumer/ChargesDeltaConsumer.java
> +        DataMapHolder.get().contextId(chsDelta.getContextId());
addressed in most recent commit

2024-10-04 11:31 UTC, crowlandsCH commented on src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
> +        DataMapHolder.get().mortgageId(chargeId);
addressed in most recent commit

2024-10-08 10:12 UTC, cgregoryCH approved these changes

2024-10-08 10:12 UTC, sthompsonCH approved these changes

2024-10-08 10:19 UTC, merged