Feature/dsnd 498 transform charges
companieshouse/charges-delta-consumer pull request #12
Opened 2022-03-18 15:47 UTC by sampipparampil

DSND-498:
Transform charges delta to charges API request

2022-03-18 17:17 UTC, gseregni-ch reviewed
I did't complete my review. Just saving this to not lose the comment. I will continue on Monday.

2022-03-21 11:02 UTC, zahidm3 requested changes

2022-03-21 11:02 UTC, zahidm3 commented on src/main/java/uk/gov/companieshouse/charges/delta/mapper/ChargeApiMapper.java
> +                chargeApi.setAssetsCeasedReleased(
Instead of switch statement, maybe easier to have Map<Integer, Enum> to take target value. But I am ok if you prefer this way as well

2022-03-21 15:22 UTC, sampipparampil commented
Addressed all the PR comments. Kindly have a look please.

2022-03-21 15:38 UTC, gseregni-ch commented on src/main/java/uk/gov/companieshouse/charges/delta/mapper/ChargeApiMapper.java
> +        chargeApi.setCreatedOn(parseDate(charge.getCreatedOn(), YYYY_MM_DD));
All good now. Thanks

2022-03-21 15:39 UTC, gseregni-ch approved these changes
All good. Thanks

2022-03-21 16:02 UTC, merged