DSND-708 Charges Delta Consumer Error/Retry Integration Test Scenarios
companieshouse/charges-delta-consumer pull request #35
Opened 2022-05-23 16:03 UTC by ipg-ch

2022-05-24 14:41 UTC, ipg-ch commented on src/main/java/uk/gov/companieshouse/charges/delta/processor/ChargesDeltaProcessor.java
> +            if ("400 Bad Request".equalsIgnoreCase(cause.getMessage())
The problem is that the clientApi throws a non retry-able exception on a 400 and a 503 so the response handler is not called and the catch block in the consumer throws it again.
As a result we dont have the status code because the client did not return but throws  the exception none retry-able exception in response to a ApiErrorResponseException (if I recall correctly)
Think it will be the same issue for Insolvency and I suspect the delete also, think might need to check that after the current bug fix.

2022-05-26 12:04 UTC, zahidm3 requested changes

2022-05-26 12:04 UTC, zahidm3 commented on src/test/resources/charges-delta-source-12.json
> -      "delivered_on":"20191017",
is there a reason delievered_on removed from all test files?

2022-05-26 13:35 UTC, ipg-ch commented on src/itest/resources/payloads/output/Insolvency_cases_Happy_Path_output.json
> +      "has_alterations_to_order": null,
Where the Boolean value does not exist in the source we get a null value int he response.  In the source file for this output particulars are set to 'no' and are false as expected in the output. Other test have 'yes' values and true in the outputs.

2022-05-26 15:06 UTC, zahidm3 approved these changes

2022-05-27 12:08 UTC, zahidm3 approved these changes

2022-05-27 12:09 UTC, merged